### PR TITLE
Create keanu.js

### PR DESCRIPTION
**Pull request by TheOnlyGhostwolf**
You're breathtaking!

Also my very first PR for Hacktoberfest.

### CODE REVIEW

**Comment by Doges** [comment]
bad news, hacktoberfest only starts tomorrow

**Comment by pedrofracassi** [comment]
how tf did the tests pass, I thought we checked for missing strings automatically :(

**Comment by TheOnlyGhostwolf** [comment]
Added strings

**Comment by TheOnlyGhostwolf** [comment]
@Doges I can literally approve my changes lol

**Pull request merged**
