### PR TITLE
Serverinfo command & logging

### LINKED ISSUE #82: Server info command

### LINKED ISSUE #121: Add better logging
+ Executed command logging
+ Joined guild
+ Left guild
+ Error logging if a command goes bork
+ etc...

### PR DESCRIPTION
**Pull request by bolsomito**
Closes #82
Closes #121

### CODE REVIEW

**Comment by bolsomito** [comment]
# Ready for review

**Comment by bolsomito** [comment]
já tá feito fdp

**Comment by pedrofracassi** [comment]
By the way

**Comment by pedrofracassi** [comment]
Why not create a LoggingListener.js file in the listeners folder?

**Comment by bolsomito** [comment]
como assim Pedro? @pedrofracassi

**Comment by pedrofracassi** [comment]
@bolsomito instead of putting those in the MainListener, create a LoggingListener instead.

**Comment by bolsomito** [comment]
Remaking this later

**Pull request closed without merging**
