### PR TITLE
Removed search-npm-registry, using API directly instead

### PR DESCRIPTION
**Pull request by almeidx**

### CODE REVIEW

**Comment by jaxxibae** [comment]
Ayy, amazing! I'll be home in about half an hour, I'll let you know if there are any changes needed. Good job o/

**Review by Doges — APPROVED** [review]
LGTM

**Comment by jaxxibae** [comment]
> Ayy, amazing! I'll be home in about half an hour, I'll let you know if there are any changes needed. Good job o/

Legend says that I'm still not home.

**Review by jaxxibae — APPROVED** [review]
Yep, LGTM.

**Pull request merged**
