### PR TITLE
Moderation Commands (pt.1)

### LINKED ISSUE #302: Mute command
I think it shouldn't be done through roles.

### LINKED ISSUE #303: Ban Command
The good old ban command

### LINKED ISSUE #304: Kick Command

### LINKED ISSUE #305: Forceban Command

### LINKED ISSUE #306: Softban Command
Bans the person, removes all of their messages and then unbans

### PR DESCRIPTION
**Pull request by bolsomito**
+ Closes #303 
+ Closes #304 
+ Closes #306

### CODE REVIEW

**Comment by pedrofracassi** [comment]
Don't we have a CommandRequirements parameter for permissions?

**Comment by bolsomito** [comment]
i guess, i'm dumb

fixing rn

**Comment by bolsomito** [comment]
umm @pedrofracassi that is for users, I

**Comment by pedrofracassi** [comment]
Can we make one for the bot?

**Comment by bolsomito** [comment]
sure

**Comment by bolsomito** [comment]
@pedrofracassi what do you

**Comment by bolsomito** [comment]
RFR

**Pull request merged**
