### PR TITLE
Add mocha tests!

### PR DESCRIPTION
**Pull request by pedrofracassi**
Closes #21 
(One of our oldest Issues!)

*What we're currently testing:*
- **Code style complies with [standard](http://github.com/standard/standard)**
- **Commands:**
  - Are in commands.json
  - Have commandDescriptions
  - Don't have any duplicate names or aliases
  - Don't have any duplicate class names

### CODE REVIEW

**Comment by pedrofracassi** [comment]
Can someone fix the NPM issues for me? I'm too tired to do it right now

**Comment by Doges** [comment]
ok, i m fixing it l8

**Comment by Doges** [comment]
ignore the vulnerability, i will add the .snyk file l8

**Comment by Doges** [comment]
ops

**Comment by Doges** [comment]
fu codacy

**Pull request merged**
