### PR TITLE
Fix #842 and redesign npm embed

### LINKED ISSUE #842: NPM search command types indefinitely
**Bug description**
```
TypeError: Cannot read property 'length' of undefined
    at Npm.handleResult (C:\Users\Pedro\WebstormProjects\switchblade\src\commands\utility\npm.js:38:22)
    at Npm.run (C:\Users\Pedro\WebstormProjects\switchblade\src\structures\command\SearchCommand.js:36:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**How to reproduce**
1. Run `s!npm speedrun --first`

**Expected behavior**
The command should show the result and not throw any errors

### PR DESCRIPTION
**Pull request by pedrofracassi**
## Changes
- Fixes #842 
- Adds `setDescriptionFromBlockArray` method to `SwitchbladeEmbed`. This method will be used later on to solve formatting issues in the chorus command.
- Redesigns the npm embed cause I thought it looked terrible.

## Screenshots
image

image

### CODE REVIEW

**Comment by pedrofracassi** [comment]
RFR!

**Comment by metehus** [comment]
doesnt RichEmbed.setDescription already supports arrays?

**Comment by pedrofracassi** [comment]
> doesnt RichEmbed.setDescription already supports arrays?

It does! But the method I made supports something I call "blocks", and formats them nicely.

**These are blocks:**
image

Blocks have a blank line between them, and if a block has no lines, its removed from the description and doesn't cause double blank lines

**Comment by metehus** [comment]
o

**Comment by dpaiv0** [comment]
should we ignore the Travis test results and approve this straight through?

**Comment by Doges** [comment]
> should we ignore the Travis test results and approve this straight through?

yea, we should ignore travis, ah wait. WE ALREADY DID IT

**Pull request merged**
