### PR TITLE
Added JetBrains Plugin Search command 

### LINKED ISSUE #1177: JetBrains Plugin Search Command
https://plugins.jetbrains.com/

### PR DESCRIPTION
**Pull request by almeidx**
Closes #1177

### CODE REVIEW

**Review by pedrofracassi — DISMISSED** [review]
LGTM

**Review by Doges — APPROVED** [review]
LGTM

**Comment by Doges** [comment]
please solve the conflicts before merging.

**Review by Doges — APPROVED** [review]
LGTM

**Review by pedrofracassi — APPROVED** [review]
LGTM

**Pull request merged**
