### PR TITLE
Database implementation

### PR DESCRIPTION
**Pull request by davipatury**
## Database implementation
- [x] `DBWrapper` class
- [x] `Repository` class

- [x] JSDoc in `DBWrapper` class
- [x] JSDoc in `Repository` class

## MongoDB
- [x] `MongoDB` class, `DBWrapper` of MongoDB databases
- [x] `MongoRepository` class, `Repository` of MongoDB databases

- [x] New `MONGODB_URI` environment variable

- [x] Schemas

### CODE REVIEW

**Comment by bolsomito** [comment]
Looks legit.

**Comment by xDoges** [comment]
foto

**Comment by xDoges** [comment]
whoops

**Comment by xDoges** [comment]
FUCK

**Comment by xDoges** [comment]
foto

**Pull request merged**
