### PR TITLE
Adds Patreon link to Botinfo command

### LINKED ISSUE #499: Add a Patreon in s!bi
image
Icon: image
Text: Donate to Me

Something like this would be good.

### PR DESCRIPTION
**Pull request by LBlend**
Closes #499

### CODE REVIEW

**Comment by LBlend** [comment]
The emote stems from my own discord server, you might wanna add it to the official switchblade server and edit the constant

**Comment by perronosaurio** [comment]
> The emote stems from my own discord server, you might wanna add it to the official switchblade server and edit the constant

we have a private server with all the emotes
image

**Comment by bolsomito** [comment]
pls invite @perronosaurio

**Comment by pedrofracassi** [comment]
Should be good to go!

**Pull request merged**
