### PR TITLE
added merriam webster dictionary command

### LINKED ISSUE #989: Merriam-Webster dictionary word definitions
`s!merriamwebster <word>`

https://dictionaryapi.com/products/api-collegiate-dictionary

### PR DESCRIPTION
**Pull request by almeidx**
Closes #989

### CODE REVIEW

**Comment by almeidx** [comment]
Fixed the conflicts and added the env variable to the wiki

**Review by Doges — APPROVED** [review]
LGTM

**Comment by Doges** [comment]
btw, resolve the conflicts

**Comment by jaxxibae** [comment]
^

**Comment by almeidx** [comment]
Done @Doges @jaxxibae

**Review by Doges — APPROVED** [review]
LGTM

**Review by Doges — APPROVED** [review]
LGTM

**Comment by almeidx** [comment]
Resolved the conflicts :)

**Review by Doges — APPROVED** [review]
LGTM

**Comment by Doges** [comment]
Nós é merecedor de curti umas férias 🥃❤️🤑

**Pull request merged**
