### PR TITLE
✨ Discord Bot List search command

### LINKED ISSUE #365: DBL Bot Info Command
`s!dbl <bot id/mention>` - Shows information from DBL about a certain bot

https://discordbots.org/api/docs

### PR DESCRIPTION
**Pull request by dpaiv0**
+ Closes #365 
image
image
image

### CODE REVIEW

**Comment by dpaiv0** [comment]
RFR

**Comment by metehus** [comment]
oh fuck

**Comment by pedrofracassi** [comment]
image

**Comment by dpaiv0** [comment]
ok

**Comment by dpaiv0** [comment]
W H Y  T H O U G H

**Comment by metehus** [comment]
> W H Y T H O U G H

lol ok

**Comment by pedrofracassi** [comment]
Yea I agree with mete, please use **SearchCommand**

**Comment by metehus** [comment]
@pedrofracassi ^^^^


_Sent from my Galaxy J7 Prime using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by pedrofracassi** [comment]
yup.

_Sent from my Philips Airfryer using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dpaiv0** [comment]
# RFR

**Comment by Doges** [comment]
the reward works?

**Comment by dpaiv0** [comment]
yes

**Pull request merged**
