### PR TITLE
[WIP] Apex Legends command

### LINKED ISSUE #708: Apex legends command
Apex legends command [apex legends](https://apex.tracker.gg/site-api)

### PR DESCRIPTION
**Pull request by Lireoy**
Closes #708

- [x] Handling user not found error
- [x] Handle invalid platform requests
- [x] List all of the legends available from a player +  lifetime stats of user
- [ ] Optional flag for returning the stats of each legend in a separate embed

### CODE REVIEW

**Comment by pedrofracassi** [comment]
You should probably remove the TODOS once you complete them instead of adding "DONE"

**Comment by Lireoy** [comment]
probably, I didn't know todo bot exists / checks code comments

**Comment by pedrofracassi** [comment]
Now you do :)

**Comment by Lireoy** [comment]
I'll need help implementing the optional flag.
Also I have a problem. When I get the response from the API, in the JSON the stats and structure is not the same all the time. This results in some empty fields when displaying lifetime stats. (Some info is not in the JSON, or some other info is the place)
image
Any idea for the approach of solving this? I have an idea which could work but I doubt that would a great code to look at.

**Comment by metehus** [comment]
IF theres no rank just put a "This player doesnt have any rank"

**Comment by Lireoy** [comment]
So here are the problems:

- I don't know what causes this, but there's a bug after a few runs on the command. The `--legends` flag just won't work.
- The data I'm getting in response from the tracker is not consistent. So this results in a bunch of no available data with new players, but fine with top players. This is due to 3rd party tracker limitations: players have to do some magic in their account to have the stats publicly visible on the tracker.
image

What are your guys' opinion on this? Also the bug? Any idea?

**Comment by davipatury** [comment]
- The flag issue has already been fixed, you should update your branch.

**Comment by Lireoy** [comment]
The data I'm getting from this API is inconsistent.
Also I'm tired of nodejs and it's black hole functionalities and worm holes in the language itself.

**Pull request closed without merging**
