### PR TITLE
✨ League of Legends command

### PR DESCRIPTION
**Pull request by dpaiv0**
+ Command translation varies through the server's language, falls back to en-US if there's no matching language
command in pt-BR
command in en-US

### CODE REVIEW

**Comment by pedrofracassi** [comment]
I'd say it should be `s!leagueoflegends champion <champ>`, cause we'll add more LoL commands in the future for sure. If that change is made, `s!lolstatus` could also become `s!leagueoflegends status`.

**Comment by dpaiv0** [comment]
### RFR

**Comment by dpaiv0** [comment]
oh yeah well thought

**Comment by dpaiv0** [comment]
### RFR

**Pull request merged**
