### PR TITLE
Fixes the singular/plural "bug" with s!pay

### LINKED ISSUE #1086: grammatical problem with pay command
**Bug description**
if you pay someone 1 switchcoin,it will say that you paid it 1 switchcoin**s** instead of 1 switchcoin

**How to reproduce**
1.Run `s!pay<user> 1`
2.The bot said `You sent 1 switchcoins to <user>`
**Expected behavior**
The bot should said `You sent 1 switchcoin to <user>`
**Screenshot**
image

### PR DESCRIPTION
**Pull request by dpaiv0**
- Fixes #1086
image

### CODE REVIEW

**Comment by fernando457829** [comment]
Why uses a type param? With i18next u can do it with "count" param.

docs: https://www.i18next.com/translation-function/plurals

**Comment by dpaiv0** [comment]
> Why uses a type param? With i18next u can do it with "count" param.
> 
> docs: [i18next.com/translation-function/plurals](https://www.i18next.com/translation-function/plurals)

will fix on my OS classes

**Comment by metehus** [comment]
how do i approve

**Comment by Doges** [comment]
> Why uses a type param? With i18next u can do it with "count" param.
> 
> docs: https://www.i18next.com/translation-function/plurals

btw, you need to open a new pr anyway

**Pull request merged**
