### PR TITLE
added wikipedia command

### LINKED ISSUE #144: Wikipedia command
https://www.npmjs.com/package/wikijs

### PR DESCRIPTION
**Pull request by almeidx**
Closes #144

### CODE REVIEW

**Review by Doges — DISMISSED** [review]
LGTM

**Comment by jaxxibae** [comment]
Resolve conflicts.

**Review by Doges — DISMISSED** [review]
legitimo

**Comment by Doges** [comment]
conflicts

**Review by metehus — DISMISSED** [review]
https://en.wiktionary.org/wiki/LGTM

**Comment by almeidx** [comment]
conflicts have been resolved

**Review by Doges — APPROVED** [review]
LGTM

**Review by metehus — APPROVED** [review]

**Pull request merged**
