### PR TITLE
lastfm top commands

### LINKED ISSUE #706: Last.fm top commands
#### Create a top command on last.fm for:
- Top artists
- Top tracks
- Top albums

#### in the periods:
- 7 days
- 1 month
- 3 months
- 6 months
- 1 year
- overall

this could be done in flags like
`s!lastfm user metye --top artists --period 1month`

### PR DESCRIPTION
**Pull request by metehus**
Closes #706 

**Changes made to the original issue:** instead of flags, its a subcommand, with a opitional parameter

image

yeah we back to bussiness

### CODE REVIEW

**Comment by pedrofracassi** [comment]
I'd change the title text to `fulano's top songs`

**Comment by pedrofracassi** [comment]
or sth similar

**Comment by metehus** [comment]
`ciclano's top tracks in a month`
`ciclano's top albums in a year`
`ciclano's top artists in 3 months` 
like that?

**Comment by metehus** [comment]
image
done, thats better

**Comment by pedrofracassi** [comment]
image

Why are we getting duplicated parenthesis?

Also maybe make the play count bold so it stands out more

**Comment by metehus** [comment]
bold or this

**Comment by pedrofracassi** [comment]
I'd say `code`

**Pull request merged**
