### PR TITLE
MATH HOTFIX

### PR DESCRIPTION
**Pull request by pedrofracassi**

### CODE REVIEW

**Review by Doges — APPROVED** [review]
LGTM

**Review by almeidx — COMMENTED** [review]
Maybe remove the command locales too?

**Comment by Doges** [comment]
> 
> 
> Maybe remove the command locales too?

We are gonna remake it but, you're right

**Review by Doges — APPROVED** [review]
> Maybe remove the command locales too?

**Comment by Doges** [comment]
bruh i approved again

**Review by Doges — CHANGES_REQUESTED** [review]
> Maybe remove the command locales too?

**Comment by metehus** [comment]
Closing this in order of #1205

**Pull request closed without merging**
