### PR TITLE
Fix MyAnimeList's studio/studios part

### LINKED ISSUE #226: c!mal „Studios” not used when multiple Studios are present
**Bug description**
The „Studios” string does not display when multiple Studios are present, „Studio” is used instead.

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run c!mal <anime with multiple studios>

**Expected behavior**
„Studios” should appear.

**Screenshots**
Multiple Studios

### PR DESCRIPTION
**Pull request by beescuit**
Closes #226

### CODE REVIEW

**Comment by pedrofracassi** [comment]
This isn't necessarry, actually

**Comment by pedrofracassi** [comment]
We can just rename `studios` to `studio_plural` in the locale file

**Comment by Doges** [comment]
f it

**Comment by beescuit** [comment]
Ok I accidentally recreated the branch cause I didn't know it was merged lul

**Comment by pedrofracassi** [comment]
Fix it the right way please

**Comment by beescuit** [comment]
done #362

**Pull request merged**
