### PR TITLE
Add emoji (emoji enlarger) command

### LINKED ISSUE #338: Add enlarge emoji command
Hy!
I'd like to request this feature to enlarge emojis.

kep

### PR DESCRIPTION
**Pull request by beescuit**
Also added EmojiParameter btw
- Closes #338

### CODE REVIEW

**Comment by Doges** [comment]
wheres the animated emojo?

**Comment by beescuit** [comment]
fucc forgot it

**Comment by beescuit** [comment]
now it's cool 👌

**Comment by perronosaurio** [comment]
solve the errors

**Pull request merged**
