### PR TITLE
Trap command

### PR DESCRIPTION
**Pull request by Doges**

### CODE REVIEW

**Comment by Doges** [comment]
HELL NO

**Comment by Doges** [comment]
DON'T APPROVE, GOD, I FORGOT THE NSFW THING

**Comment by pedrofracassi** [comment]
I'll reject this as the word "trap" is one of the many kinds of transphobia that we normalize daily. We're not merging this.

**Comment by Doges** [comment]
EXCUSE ME

**Comment by Doges** [comment]
WTF

**Pull request closed without merging**
