### PR TITLE
Fixed waifu.pics API

### PR DESCRIPTION
**Pull request by Riku32**
Fixed waifu and neko command.

### CODE REVIEW

**Review by almeidx — APPROVED** [review]

**Review by almeidx — COMMENTED** [review]
fix ci first tho

**Comment by Riku32** [comment]
Fixed the CI checks

**Review by almeidx — APPROVED** [review]
LGTM

**Review by Tsugami — APPROVED** [review]
LGTM

**Review by fernando457829 — APPROVED** [review]
LGTM

**Pull request merged**
