### PR TITLE
Nowplaying canvas command

### PR DESCRIPTION
**Pull request by davipatury**
Design made by @WillianRod 
preview
- Needs default song image

### CODE REVIEW

**Comment by WillianRod** [comment]
## Design sugestion
I made a re-design of this. I hope you liked. May have a little problem with youtube thumbnails, but there are ways around it
Sugestion design

**Comment by beescuit** [comment]
HOLY SHIT

**Comment by bolsomito** [comment]
HOLY SHIT²

**Comment by pedrofracassi** [comment]
There's just no fucking way that you've already done it, davi

**Comment by Doges** [comment]
you still need help?

**Comment by davipatury** [comment]
no

**Comment by davipatury** [comment]
review pls

**Pull request merged**
