### PR TITLE
Adds Bitcoin value command

### PR DESCRIPTION
**Pull request by LBlend**
I guess you can expand this in the future to support more cryptocurrencies

### CODE REVIEW

**Comment by pedrofracassi** [comment]
Yoo! Nice!

**Comment by pedrofracassi** [comment]
`Maybe the embed could look like this:`

**Current Bitcoin value**
1 BTC = X USD

**Comment by pedrofracassi** [comment]
Also, how about allowing the user to pass their own currency, but default to USD?

**Comment by LBlend** [comment]
I'm gonna change the embed and fix the errors that Codacy and travis are giving

**Comment by LBlend** [comment]
england hard very yes

**Comment by Doges** [comment]
> @Doges and is it due to..?

also, i don't like the only USD thingy

**Comment by pedrofracassi** [comment]
Yeah, we can totally change that.

**Comment by Doges** [comment]
Resubmitting this as #512

**Comment by pedrofracassi** [comment]
poor blendey

**Pull request closed without merging**
