### PR TITLE
Mixer integration

### LINKED ISSUE #679: Mixer nowplaying
image

### PR DESCRIPTION
**Pull request by davipatury**
Closes #679 

img

### CODE REVIEW

**Comment by pedrofracassi** [comment]
I've moved some colors to `Constants`, but there are still some hardcoded ones. Can someone move them for me?

**Comment by dpaiv0** [comment]
There's one on beatsaver.js

**Comment by pedrofracassi** [comment]
Most of the Song service classes still have hardcoded colors

**Comment by metehus** [comment]
i think its done

**Pull request merged**
