### PR TITLE
Chore: Chalk

### LINKED ISSUE #1080: Why not use Chalk instead of ansi escapes?
The code would much better with chalk:
```js
client.log('[36mHello World') // without Chalk
client.log(chalk.cyan('Hello World') // with Chalk
```

And we could add options on `client.log`, for example:
```js
client.log('Hello World', { tags: ['Test'], color: 'cyan' })
```

### PR DESCRIPTION
**Pull request by fernando457829**
closes #1080

### CODE REVIEW

**Comment by pedrofracassi** [comment]
É pra chorar

**Comment by fernando457829** [comment]
> whats chore?

I try to follow the [@commitlint/config-conventional](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional) rules to standardize my commits and **chore** is a type of commit according this rules. The differences between feat and chore (from what I understand):
**feat:** new feature
**chore:** modification, but not a new feature

**Comment by fernando457829** [comment]
> É pra chorar

asdfhauifdshsdfaadfshjadsf

**Comment by metehus** [comment]
@fernando457829 fds épra chora

**Pull request merged**
