### PR TITLE
Added How Long To Beat Command

### LINKED ISSUE #1265: HowLongToBeat command
https://www.npmjs.com/package/howlongtobeat

> How long are your favorite video games? HowLongToBeat has the answer. Create a backlog, submit your game times and compete with your friends!

`s!howlongtobeat <game>`

### PR DESCRIPTION
**Pull request by Eroxl**
Added the how long to beat command

Closes #1265

### CODE REVIEW

**Comment by Eroxl** [comment]
I just upgraded npm and it's still doing to the same thing would you mind giving me the version number you're using?

**Comment by Eroxl** [comment]
Sorry about that I didn't even notice. I think it should be fixed now though.

**Comment by almeidx** [comment]
You don't need to edit the lockfile manually by the way (Referring to your latest commit)

Just run `npm install` and leave it at that

**Comment by Eroxl** [comment]
Ok thanks

**Pull request merged**
