### PR TITLE
Weather units

### PR DESCRIPTION
**Pull request by metehus**
### Now `s!weather` displays the unit

unit

### CODE REVIEW

**Comment by pedrofracassi** [comment]
image

**Comment by metehus** [comment]
i dont think it need in all units, i think in the main temperature already says its all in celsius or whatever

**Comment by dpaiv0** [comment]
sim, mas bota ºC de qualquer das formas, pra não causar confusão

**Comment by pedrofracassi** [comment]
tbh actually we could remove decimals for good

**Comment by metehus** [comment]
just for the daily then

**Pull request merged**
