### PR TITLE
Adds leaderboard command

### LINKED ISSUE #367: Top 10 richest people command
`s!moneytop`

### PR DESCRIPTION
**Pull request by davipatury**
- Closes #367

money
reputation

### CODE REVIEW

**Comment by perronosaurio** [comment]
this is a concept
concept

**Comment by pedrofracassi** [comment]
YO THAT LOOKS BEAUTIFUL

**Comment by pedrofracassi** [comment]
I like how Davi says "maybe **I** could use canvas", cause he know he's the only one who has balls to mess with it

**Comment by perronosaurio** [comment]
XD

**Comment by Doges** [comment]
what do you need help?

**Comment by pedrofracassi** [comment]
How is this going?

**Comment by pedrofracassi** [comment]
What still needs to be done here?

**Comment by davipatury** [comment]
RFR

**Pull request merged**
