### PR TITLE
Adds role list command

### LINKED ISSUE #79: Role list command (with IDs)

### PR DESCRIPTION
**Pull request by moruzerinho6**
image

This closes #79

I still need help to remove the "Loading" message after the embed is sent.

### CODE REVIEW

**Comment by metehus** [comment]
i found that style kinds messy
image

**Comment by davipatury** [comment]
[Something similitar to this](https://github.com/SwitchbladeBot/switchblade/pull/1139#issuecomment-670812475)

**Comment by fernando457829** [comment]
LGTM

**Review by pedrofracassi — APPROVED** [review]
LGTM

**Pull request merged**
