### PR TITLE
vem 🏎 de zap 📞📞📱 bb 💘

### LINKED ISSUE #417: Zap Command
http://vemdezapbe.be

### PR DESCRIPTION
**Pull request by pedrofracassi**
Adds the `s!zap` command

Closes #417

### CODE REVIEW

**Comment by pedrofracassi** [comment]
Yeah, we could do that

**Comment by bolsomito** [comment]
And, while you're at it, you can choose the zapzap mood and its intensity, like @LorittaBot does

**Comment by Doges** [comment]
> I think it would be interesting if it had a "raw" argument that would return the Unicode emojis in a codeblock so we can copypasta it in zapzap

@perronosaurio

**Comment by pedrofracassi** [comment]
What still needs to be done for this to be merged?

**Comment by Doges** [comment]
the reaction thingy

**Comment by pedrofracassi** [comment]
Will redo this from the ground up. Closing.

**Pull request closed without merging**
