### PR TITLE
Adds the Steam Ladder command

### PR DESCRIPTION
**Pull request by pedrofracassi**
## New API wrappers
- **SteamAPI** (requires `STEAM_API_KEY`)
- **SteamLadderAPI** (requires `STEAM_LADDER_API_KEY`)

## New commands
- Adds the **Steam Ladder** command (requires `SteamAPI`)

## Others
- **i18next** is now accessible through the client
- Added **EmojiUtils**, home to the `getFlag` function
- Added SteamLadder badge emoji to the **Constants** file
- Added a [polyfill](https://npmjs.com/package/intl) for **Intl**, as node doesn't come with any locales other than English.
- Fixed some missing `#`s on some colors

## Screenshots
image
image

### CODE REVIEW

**Comment by pedrofracassi** [comment]
Closes #443

**Comment by Doges** [comment]
@Lireoy thats a codacy problem lmao, its up to standard

**Comment by Lireoy** [comment]
was worth a try

**Comment by Doges** [comment]
done, its checking again

**Comment by davipatury** [comment]
Is this RFR?

**Comment by pedrofracassi** [comment]
yes!

**Comment by pedrofracassi** [comment]
codacy glitched, tho

**Comment by Doges** [comment]
@pedrofracassi solve the conflicts and force merge this if needed.

**Pull request merged**
